git-utils status command & script cleaning

diff --git a/scripts/git-utils b/scripts/git-utils
--- a/scripts/git-utils
+++ b/scripts/git-utils
@@ -6,11 +6,11 @@
 
 function makeDirectoryIfInexistant()
 {
-    DIR=$1
-    if [ ! -d $DIR ]
+    directory=$1
+    if [ ! -d $directory ]
     then
-        echo "Making repos directory $DIR"
-        mkdir -p $DIR
+        echo "Making repos directory $directory"
+        mkdir -p $directory
     fi
 }
 
@@ -18,13 +18,13 @@ function makeDirectoryIfInexistant()
 
 function ensureProgramIsInstalled()
 {
-    PROG=$1
-    if [ -z $(which $PROG) ]
+    program_name=$1
+    if [ -z $(which $program_name) ]
     then
-        echo "$PROG is needed to work with json"
+        echo "$program_name program is needed"
         echo "you can install it with"
         echo ""
-        echo "sudo apt install $PROG"
+        echo "sudo apt install $program_name"
         exit 1
     fi
 }
@@ -35,7 +35,13 @@ function ensureProgramIsInstalled()
 
 
 
-
+#    ###    ########  ####    ##    ## ######## ##    ##
+#   ## ##   ##     ##  ##     ##   ##  ##        ##  ##
+#  ##   ##  ##     ##  ##     ##  ##   ##         ####
+# ##     ## ########   ##     #####    ######      ##
+# ######### ##         ##     ##  ##   ##          ##
+# ##     ## ##         ##     ##   ##  ##          ##
+# ##     ## ##        ####    ##    ## ########    ##
 
 
 function getGitApiTokenPath()
@@ -66,46 +72,85 @@ function registerToken()
     echo "Done."
 }
 
+function testToken()
+{
+    GITUTILS_API_KEY_PATH=$(getGitApiTokenPath)
+    if [ -f $GITUTILS_API_KEY_PATH ]
+    then
+        api_key=$(getGitApiToken)
+        echo "Registered Api key : $api_key"
+
+        response=$(curl -L -s \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $api_key" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/user/repos)
+
+        url=$(echo "$response" | jq -r .[].full_name)
+
+        if [ "$url" = "null" ]
+        then
+            echo "Status: Invalid or expired"
+        else
+            echo "Status: Valid"
+        fi
+
+    else
+        echo "API Key is not configured (you can register one with 'git-utils register-key <key>')"
+    fi
+}
 
 
 
+
+
+
+
+
+
+# ########  ######## ########   #######   ######
+# ##     ## ##       ##     ## ##     ## ##    ##
+# ##     ## ##       ##     ## ##     ## ##
+# ########  ######   ########  ##     ##  ######
+# ##   ##   ##       ##        ##     ##       ##
+# ##    ##  ##       ##        ##     ## ##    ##
+# ##     ## ######## ##         #######   ######
 
 
 function createRepo()
 {
     ensureProgramIsInstalled "jq"
 
-    REPO_NAME=$1
-    API_TOKEN=$(getGitApiToken)
+    repo_name=$1
+    api_token=$(getGitApiToken)
 
+    echo "Create repo $repo_name..."
 
-    echo "Create repo $REPO_NAME..."
-
-    OUTPUT=$(curl -L -s \
+    output=$(curl -L -s \
       -X POST \
       -H "Accept: application/vnd.github+json" \
-      -H "Authorization: Bearer $API_TOKEN" \
+      -H "Authorization: Bearer $api_token" \
       -H "X-GitHub-Api-Version: 2022-11-28" \
       https://api.github.com/user/repos \
-      -d "{\"name\":\"$REPO_NAME\",\"private\":true}")
+      -d "{\"name\":\"$repo_name\",\"private\":true}")
 
-    URL=$(echo "$OUTPUT" | jq -r ".html_url")
+    url=$(echo "$output" | jq -r ".html_url")
 
-    if [ "$URL" = "null" ]
+    if [ "$url" = "null" ]
     then
         echo "URL NOT FOUND !"
         echo "Please ensure that there is no error with curl"
         echo "Here is the curl output"
-        echo "$OUTPUT"
+        echo "$output"
         exit 1
     fi
 
-    REPO_NAME=$(echo "$OUTPUT" | jq -r ".full_name")
-    REPO_PATH="$GITUTILS_REPOS_PATH/$REPO_NAME"
-    OG_PWD=$(pwd)
+    repo_name=$(echo "$output" | jq -r ".full_name")
+    repo_path="$GITUTILS_REPOS_PATH/$repo_name"
+    og_path=$(pwd)
 
-    git clone $URL $REPO_PATH
-    cd $REPO_PATH
+    git clone $URL $repo_path
+    cd $repo_path
 
 
     read -p "Add Sharp Framework (y/n) ? " -n 1 -r
@@ -143,34 +188,260 @@ function createRepo()
     echo
     if [[ $REPLY =~ ^[Yy]$ ]]
     then
-        REPO_BASENAME=$(basename $REPO_NAME)
-        REPO_SYMLINK="$HOME_PATH/Desktop/$REPO_BASENAME"
+        repo_basename=$(basename $repo_name)
+        repo_symlink="$HOME_PATH/Desktop/$repo_basename"
 
-        if [ -L $REPO_SYMLINK ]
+        if [ -L $repo_symlink ]
         then
-            echo "It seems that $REPO_SYMLINK already exists !"
+            echo "It seems that $repo_symlink already exists !"
             echo "Please remove it before creating it again"
             echo "rm $SYMLINK_PATH"
-            echo "ln -s \"$REPO_PATH\" \"$REPO_SYMLINK\""
+            echo "ln -s \"$repo_path\" \"$repo_symlink\""
         else
-            ln -s "$REPO_PATH" "$REPO_SYMLINK"
-            echo "Created symlink at $REPO_SYMLINK !"
+            ln -s "$repo_path" "$repo_symlink"
+            echo "Created symlink at $repo_symlink !"
         fi
 
     fi
 
     echo
     echo "---------------------------"
-    echo "Repo $REPO_NAME successfuly created & pushed !"
+    echo "Repo $repo_name successfuly created & pushed !"
     echo "Url  : $URL"
-    echo "Path : $REPO_PATH"
+    echo "Path : $repo_path"
     echo "---------------------------"
     echo
 
-    cd $OG_PWD
+    cd $og_path
 }
 
 
+
+function listInstalledRepos()
+{
+    echo "Repositories inside $GITUTILS_REPOS_PATH"
+    authors=$(ls -1 $GITUTILS_REPOS_PATH)
+
+    for author in $authors
+    do
+        author_path="$GITUTILS_REPOS_PATH/$author"
+        repos=$(ls -1 $author_path)
+
+        echo
+        echo "$author"
+
+        for repo in $repos
+        do
+            echo " - $author/$repo"
+        done
+    done
+}
+
+function listUserRepos()
+{
+    api_token=$(getGitApiToken)
+
+    response=$(curl -L -s \
+        -H "Accept: application/vnd.github+json" \
+        -H "Authorization: Bearer $api_token" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        https://api.github.com/user/repos)
+
+    url=$(echo "$response" | jq -r .[].full_name)
+
+    if [ "$url" = "null" ]
+    then
+        echo "URLs NOT FOUND !"
+        echo "Please ensure that there is no error with curl"
+        echo "Here is the curl output"
+        echo "$response"
+        exit 1
+    fi
+
+    echo "Availables repositories to clone"
+
+    for repo_name in $url
+    do
+        repo_potential_path="$GITUTILS_REPOS_PATH/$repo_name"
+        if [ -d $repo_potential_path ]
+        then
+            echo " - $repo_name (Installed)"
+        else
+            echo " - $repo_name (Not Installed)"
+        fi
+
+    done
+}
+
+function cloneAllRepositories()
+{
+    api_token=$(getGitApiToken)
+
+    response=$(curl -L -s \
+        -H "Accept: application/vnd.github+json" \
+        -H "Authorization: Bearer $api_token" \
+        -H "X-GitHub-Api-Version: 2022-11-28" \
+        https://api.github.com/user/repos)
+
+    url=$(echo "$response" | jq -r .[].full_name)
+
+    if [ "$url" = "null" ]
+    then
+        echo "URLs NOT FOUND !"
+        echo "Please ensure that there is no error with curl"
+        echo "Here is the curl output"
+        echo "$OUTPUT"
+        exit 1
+    fi
+
+    for repo_name in $url
+    do
+        echo "Cloning $repo_name"
+
+        repo_directory="$GITUTILS_REPOS_PATH/$repo_name"
+
+        if [ -d $repo_directory ]
+        then
+            echo "Skipping, $repo_directory directory already exists"
+        else
+            git clone "https://github.com/$repo_name" "$repo_directory" --recursive
+        fi
+
+        echo
+
+    done
+
+}
+
+
+
+function pullAllrepos()
+{
+    echo "Repositories inside $GITUTILS_REPOS_PATH"
+    authors=$(ls -1 $GITUTILS_REPOS_PATH)
+
+    og_path=$(pwd)
+
+    for author in $authors
+    do
+        author_path="$GITUTILS_REPOS_PATH/$author"
+        repos=$(ls -1 $author_path)
+
+        echo
+        echo "$author"
+
+        for repo in $repos
+        do
+            repo_path="$author_path/$repo"
+            cd $repo_path
+            output=$(git status)
+
+            if [[ "$output" =~ "Changes not staged" ]]
+            then
+                echo " - $repo : please commit before pulling"
+            else
+                echo " - $repo : pulling"
+                git pull
+                echo
+            fi
+        done
+    done
+
+    cd $og_path
+}
+
+
+function getStatus()
+{
+    VERBOSE_MODE=0
+    EDITED_ONLY=0
+
+    for param in $*
+    do
+        case $param in
+            -v|--verbose)
+                VERBOSE_MODE=1
+            ;;
+            -e|--edited)
+                EDITED_ONLY=1
+            ;;
+        esac
+    done
+
+
+    echo "-------------------------------"
+    echo "   Local repositories status"
+    echo "-------------------------------"
+    echo
+
+    og_path=$(pwd)
+    local_repos_list=$(ls $GITUTILS_REPOS_PATH/*/* -1d)
+
+    if [ "$VERBOSE_MODE" = "1" ]
+    then
+        repos_count=$(echo "$local_repos_list" | wc -l)
+        repos_increment=0
+        for directory in $local_repos_list
+        do
+            repos_increment=$((repos_increment+1))
+
+            cd $directory
+            git_repo_user=$(basename $(realpath ..))
+            git_repo_name=$(basename $(realpath .))
+
+            has_changes=$(git status | grep -E 'Changes not staged|Your branch is ahead' | wc -l)
+
+            if [ "$has_changes" = "0" ] && [ "$EDITED_ONLY" = "1" ]
+            then
+                continue
+            fi
+
+            echo -e -n "\e[30;46m$repos_increment/$repos_count Status of $git_repo_user/$git_repo_name\e[0m"
+            echo
+
+            git status
+
+            echo
+            echo -e -n "\e[30;47mPress a key to continue, press Ctrl+C to exit\e[0m"
+            read -N1
+            echo -e "\e[1Am\e[2K"
+
+        done
+    else
+        for directory in $local_repos_list
+        do
+            cd $directory
+            git_repo_user=$(basename $(realpath ..))
+            git_repo_name=$(basename $(realpath .))
+
+            has_changes=$(git status | grep -E 'Changes not staged|Your branch is ahead' | wc -l)
+
+            if [ ! "$has_changes" = "0" ]
+            then
+                echo -e "\e[1;33m[EDITED] $git_repo_user/$git_repo_name has changes to commit/push \e[0m"
+            elif [ "$EDITED_ONLY" = "0" ]
+            then
+                echo -e "\e[1;32m[UTD]\e[0m $git_repo_user/$git_repo_name is up to date"
+            fi
+        done
+    fi
+
+    echo
+    cd "$og_path"
+
+
+}
+
+
+
+
+#  ######  ########  ######## ########   ######
+# ##    ## ##     ## ##       ##     ## ##    ##
+# ##       ##     ## ##       ##     ## ##
+# ##       ########  ######   ##     ##  ######
+# ##       ##   ##   ##       ##     ##       ##
+# ##    ## ##    ##  ##       ##     ## ##    ##
+#  ######  ##     ## ######## ########   ######
 
 function enableCredentialCache()
 {
@@ -186,174 +457,50 @@ function disableCredentialCache()
 
 
 
-function listInstalledRepos()
-{
-    echo "Repositories inside $GITUTILS_REPOS_PATH"
-    AUTHORS=$(ls -1 $GITUTILS_REPOS_PATH)
 
-    for AUTHOR in $AUTHORS
-    do
-        AUTHOR_PATH="$GITUTILS_REPOS_PATH/$AUTHOR"
-        REPOS=$(ls -1 $AUTHOR_PATH)
 
-        echo
-        echo "$AUTHOR"
 
-        for REPO in $REPOS
-        do
-            echo " - $AUTHOR/$REPO"
-        done
-    done
-}
-
-function listUserRepos()
-{
-    API_TOKEN=$(getGitApiToken)
-
-    RES=$(curl -L -s \
-        -H "Accept: application/vnd.github+json" \
-        -H "Authorization: Bearer $API_TOKEN" \
-        -H "X-GitHub-Api-Version: 2022-11-28" \
-        https://api.github.com/user/repos)
-
-    URL=$(echo "$RES" | jq -r .[].full_name)
-
-    if [ "$URL" = "null" ]
-    then
-        echo "URLs NOT FOUND !"
-        echo "Please ensure that there is no error with curl"
-        echo "Here is the curl output"
-        echo "$OUTPUT"
-        exit 1
-    fi
-
-    echo "Availables repositories to clone"
-
-    for REPO_NAME in $URL
-    do
-        REPO_POTENTIAL_PATH="$GITUTILS_REPOS_PATH/$REPO_NAME"
-        if [ -d $REPO_POTENTIAL_PATH ]
-        then
-            echo " - $REPO_NAME (Installed)"
-        else
-            echo " - $REPO_NAME (Not Installed)"
-        fi
-
-    done
-}
-
+#  ######  ##    ## ##     ## ##       #### ##    ## ##    ##
+# ##    ##  ##  ##  ###   ### ##        ##  ###   ## ##   ##
+# ##         ####   #### #### ##        ##  ####  ## ##  ##
+#  ######     ##    ## ### ## ##        ##  ## ## ## #####
+#       ##    ##    ##     ## ##        ##  ##  #### ##  ##
+# ##    ##    ##    ##     ## ##        ##  ##   ### ##   ##
+#  ######     ##    ##     ## ######## #### ##    ## ##    ##
 
 function createDesktopSymlink()
 {
-    REPO_NAME=$1
+    repo_name=$1
 
-    if [ ! -z "$REPO_NAME" ]
+    if [ ! -z "$repo_name" ]
     then
-        REPO_BASENAME=$(basename $REPO_NAME)
-        SYMLINK_TARGET="$GITUTILS_REPOS_PATH/$REPO_NAME"
-        SYMLINK_PATH="$HOME_PATH/Desktop/$REPO_BASENAME"
+        repo_basename=$(basename $repo_name)
+        symlink_target="$GITUTILS_REPOS_PATH/$repo_name"
+        symlink_path="$HOME_PATH/Desktop/$repo_basename"
     else
-        SYMLINK_TARGET=$GITUTILS_CONFIG_PATH
-        SYMLINK_PATH="$HOME_PATH/Desktop/repositories"
+        symlink_target=$GITUTILS_CONFIG_PATH
+        symlink_path="$HOME_PATH/Desktop/repositories"
     fi
 
-    if [ ! -d $SYMLINK_TARGET ]
+    if [ ! -d $symlink_target ]
     then
-        echo "Error ! Symlink target $SYMLINK_TARGET does not exists"
+        echo "Error ! Symlink target $symlink_target does not exists"
         exit 1
     fi
 
-    if [ -L $SYMLINK_PATH ]
+    if [ -L $symlink_path ]
     then
-        echo "It seems that $SYMLINK_PATH already exists !"
+        echo "It seems that $symlink_path already exists !"
         echo "Please remove it before creating it again"
-        echo "rm $SYMLINK_PATH"
+        echo "rm $symlink_path"
         exit 1
     fi
 
-    ln -s "$SYMLINK_TARGET" "$SYMLINK_PATH"
-    echo "Created symlink $SYMLINK_PATH"
-    echo "leading to $SYMLINK_TARGET"
+    ln -s "$symlink_target" "$symlink_path"
+    echo "Created symlink $symlink_path"
+    echo "leading to $symlink_target"
 }
 
-
-
-function cloneAllRepositories()
-{
-    API_TOKEN=$(getGitApiToken)
-
-    RES=$(curl -L -s \
-        -H "Accept: application/vnd.github+json" \
-        -H "Authorization: Bearer $API_TOKEN" \
-        -H "X-GitHub-Api-Version: 2022-11-28" \
-        https://api.github.com/user/repos)
-
-    URL=$(echo "$RES" | jq -r .[].full_name)
-
-    if [ "$URL" = "null" ]
-    then
-        echo "URLs NOT FOUND !"
-        echo "Please ensure that there is no error with curl"
-        echo "Here is the curl output"
-        echo "$OUTPUT"
-        exit 1
-    fi
-
-    for REPO_NAME in $URL
-    do
-        echo "Cloning $REPO_NAME"
-
-        REPO_DIRECTORY="$GITUTILS_REPOS_PATH/$REPO_NAME"
-
-        if [ -d $REPO_DIRECTORY ]
-        then
-            echo "Skipping, $REPO_DIRECTORY directory already exists"
-        else
-            git clone "https://github.com/$REPO_NAME" "$REPO_DIRECTORY" --recursive
-        fi
-
-        echo
-
-    done
-
-}
-
-
-
-function pullAllrepos()
-{
-    echo "Repositories inside $GITUTILS_REPOS_PATH"
-    AUTHORS=$(ls -1 $GITUTILS_REPOS_PATH)
-
-    OG_PATH=$(pwd)
-
-    for AUTHOR in $AUTHORS
-    do
-        AUTHOR_PATH="$GITUTILS_REPOS_PATH/$AUTHOR"
-        REPOS=$(ls -1 $AUTHOR_PATH)
-
-        echo
-        echo "$AUTHOR"
-
-        for REPO in $REPOS
-        do
-            REPO_PATH="$AUTHOR_PATH/$REPO"
-            cd $REPO_PATH
-            OUTPUT=$(git status)
-
-            if [[ "$OUTPUT" =~ "Changes not staged" ]]
-            then
-                echo " - $REPO : please commit before pulling"
-            else
-                echo " - $REPO : pulling"
-                git pull
-                echo
-            fi
-        done
-    done
-
-    cd $OG_PATH
-}
 
 
 function displayHelp()
@@ -362,17 +509,28 @@ function displayHelp()
     echo ""
     echo "Available Commands"
     echo
+    echo " register-key <API_KEY>"
+    echo "     Register a new GitHub api token"
+    echo
+    echo " get-key"
+    echo "     Get the registered GitHub api token"
+    echo
+    echo " test-key"
+    echo "     Test the registered GitHub api token"
+    echo
     echo " make <PROJECT_NAME>"
     echo "     Make a repository, can install Sharp & SharpExtensions if wanted"
     echo
     echo " clone-all"
     echo "     Clone all of your repositories"
     echo
-    echo " register-key <API_KEY>"
-    echo "     Register a new GitHub api token"
+    echo " pull-all"
+    echo "     Pull all locally installed repositories"
     echo
-    echo " get-key"
-    echo "     Get the registered GitHub api token"
+    echo " status"
+    echo "     Display the status of local repos"
+    echo "         -e|--edited to display repos that needs commits/pushes only"
+    echo "         -v|--verbose to display full git status"
     echo
     echo " enable-cache"
     echo "     Enable the credential store cache"
@@ -391,9 +549,6 @@ function displayHelp()
     echo
     echo " list-dist"
     echo "     List all availables repos"
-    echo
-    echo " pull-all"
-    echo "     Pull all locally installed repositories"
     echo
     echo " help"
     echo "     Display this help message"
@@ -428,6 +583,10 @@ case $COMMAND in
         echo ""
     ;;
 
+    test-key)
+        testToken
+    ;;
+
     enable-cache)
         enableCredentialCache
     ;;
@@ -460,6 +619,10 @@ case $COMMAND in
         pullAllrepos
     ;;
 
+    status)
+        getStatus $*
+    ;;
+
     *)
         echo "Unknown command '$1'"
         exit 1
@@ -467,5 +630,4 @@ case $COMMAND in
 esac
 
 echo
-
 exit 0
