better gxi behavior

diff --git a/modules/scripts/git/gxi b/modules/scripts/git/gxi
--- a/modules/scripts/git/gxi
+++ b/modules/scripts/git/gxi
@@ -1,21 +1,29 @@
 #!/bin/sh
 
-set -euo pipefail
+echo "Git repo status : "
+git status --short | grep -v -E "^ +\?.+$"
+git log --branches --not --remotes --decorate=short --pretty=format:'%D' | sed 's/^HEAD -> //g' | sort -u
+echo ""
 
-if ! utilux-prompt --prompt "⚠️  Warning ! This command will perform a git reset --hard, you will lose any un-pushed work ! Continue ?"; then 
-    echo "❌ Aborted."
-    exit 1
-fi
+echo "⚠️  Warning ! This command will perform a git reset --hard ON EVERY BRANCHES, you will lose any un-pushed work !"
 
-echo
-echo "🧹 Cleaning up your repo..."
-git reset --hard
-git clean -fd
-gxpm
+printf "Continue ? [y/N] "
+read reply
+case "$(printf "%s" "$reply" | cut -c1)" in
+    [Yy]) ;;
+    *) echo "Aborted."; exit 1 ;;
+esac
 
 echo
 echo "📥 Retrieving missing work (1/2)..."
 gxf
+
+echo
+echo "🧹 Cleaning up your repo..."
+gxc main
+git clean -fd
+gxpm
+
 
 echo
 echo "🔁 Syncing remote branch with local..."
@@ -39,7 +47,7 @@ echo "📥 Retrieving missing work (2/2)..."
 original_branch=$(gxb)
 git for-each-ref --format='%(refname:short)' refs/heads | while read branch ; do
     git checkout "$branch" >/dev/null
-    git pull >/dev/null && echo "Branch pulled successfuly"
+    git reset --hard "origin/$branch" && echo "Branch synced successfuly"
 done
 git checkout "$original_branch"
 
