Better gxi script

diff --git a/modules/scripts/git/gxi b/modules/scripts/git/gxi
--- a/modules/scripts/git/gxi
+++ b/modules/scripts/git/gxi
@@ -12,6 +12,11 @@ echo "🧹 Cleaning up your repo..."
 git reset --hard
 git clean -fd
 
+
+echo
+echo "📥 Retrieving missing work (1/2)..."
+gxf
+
 echo
 echo "🔁 Syncing remote branch with local..."
 git for-each-ref --format='%(refname:short)' refs/heads | while read branch ; do
@@ -20,8 +25,9 @@ git for-each-ref --format='%(refname:short)' refs/heads | while read branch ; do
     fi
 
     if git show-ref --verify --quiet "refs/remotes/origin/$branch"; then
-        git branch --set-upstream-to="origin/$branch" "$branch"
-        echo "🔗 Bound ${branch} to origin/${branch}"
+        git branch --set-upstream-to="origin/$branch" "$branch" 2>&1 >/dev/null \
+         && echo "🔗 Bound ${branch} to origin/${branch}" \
+         || echo "⚠️ Could not bind ${branch} to origin/${branch}"
     else
         echo "⚠️  No remote : ${branch}"
     fi
@@ -29,10 +35,8 @@ git for-each-ref --format='%(refname:short)' refs/heads | while read branch ; do
 done
 
 echo
-echo "📥 Retrieving missing work..."
-gxf
+echo "📥 Retrieving missing work (2/2)..."
 git pull --all
-
 
 echo
 echo "✅ Your repo is now ready to work with !"
