Improving installation process

diff --git a/modules/scripts/git/gxi b/modules/scripts/git/gxi
--- a/modules/scripts/git/gxi
+++ b/modules/scripts/git/gxi
@@ -1,30 +1,26 @@
-#!/bin/bash
+#!/bin/sh
 # git init - make your projet fresh to start something
 
 set -euo pipefail
 
 # Couleurs pour un affichage stylé
-RED="\033[0;31m"
-GREEN="\033[0;32m"
-YELLOW="\033[1;33m"
-NC="\033[0m" # No Color
 
-echo -e "${YELLOW}⚠️  Warning ! This command will perform a git reset --hard${NC}"
+echo "⚠️  Warning ! This command will perform a git reset --hard"
 read -p "Proceed ? [y/N]:" -n 1 -r
 echo
 
-if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-    echo -e "${RED}❌ Aborted.${NC}"
+if ! echo "$REPLY" | grep -E '^[Yy]$' > /dev/null; then
+    echo "❌ Aborted."
     exit 1
 fi
 
 echo
-echo -e "${GREEN}🧹 Cleaning up your repo...${NC}"
+echo "🧹 Cleaning up your repo..."
 git reset --hard
 git clean -fd
 
 echo
-echo -e "${GREEN}🔁 Syncing remote branch with local...${NC}"
+echo "🔁 Syncing remote branch with local..."
 git for-each-ref --format='%(refname:short)' refs/heads | while read branch ; do
     if [ "$branch" = "main" ]; then
         continue
@@ -32,18 +28,18 @@ git for-each-ref --format='%(refname:short)' refs/heads | while read branch ; do
 
     if git show-ref --verify --quiet "refs/remotes/origin/$branch"; then
         git branch --set-upstream-to="origin/$branch" "$branch"
-        echo -e "🔗 Upstream defined for ${branch} → origin/${branch}"
+        echo "🔗 Upstream defined for ${branch} → origin/${branch}"
     else
-        echo -e "${YELLOW}⚠️  No remote branch for ${branch}${NC}"
+        echo "⚠️  No remote branch for ${branch}"
     fi
 
 done
 
 echo
-echo -e "${GREEN}📥 Retrieving missing work...${NC}"
+echo "📥 Retrieving missing work..."
 gxf
 git pull --all
 
 
 echo
-echo -e "${GREEN}✅ Your repo is now ready to work with !${NC}"
+echo "✅ Your repo is now ready to work with !"
